name: CI
on:
  push:
    branches-ignore:
      - 'gh-pages'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install yarn@1.17.3
    - run: yarn install
    - run: yarn re:build
    - run: yarn build
    - run: yarn test
      env:
        CI: true
    - name: Deploy
      run: |
        git config user.email "pewniak747+minesweeper-reasonml@gmail.com"
        git config user.name "deploy"
        yarn deploy
